# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: flyinglove
email: 446419676@qq.com
description:  # this means to ignore newlines until "baseurl:"
  ## Write an awesome description for your new site here. You can edit this
  ## line in _config.yml. It will appear in your document head meta (for
  ## Google search results) and in your feed.xml site description.
  Hello,This is my first trying to create a blog on my own and for myself,and I will finished it as soon as I can!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hello-front-end.github." # the base hostname & protocol for your site
twitter_username: flyinglove
github_username:  hello-front-end

# Build settings
markdown: kramdown
highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false
encoding: utf-8
